### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by TetsuyaSuzuki** [Team-Hycon/hycon-gui#13]
My HYCON isn't reflected by wallet.
When wallet of a main page is clicked.
wallet.hycon.io is no longer supported.
For your safety and security, please visit our Medium article for instructions to claim your wallet for coin distribution. 

Indication goes out.
When (https://medium.com/@teamhycon/hycon-coin-distribution-b8e84f02e079) was clicked and it was made a procedure street, but that 

tries to input passward to the back command screen which clicked lunch for step 5, a command screen goes off, and I can't process it 

until the end.
How should it be done to pay HYC in HYCON wallet? I'm very worried.

It was operated as you told me in Telegram a short while ago but HYCON Wallet is indicating (HYCON PROCESSED Pending SENT AMOUNT 0 HYC). Is it said that HYC isn't in Wallet for this? I don't understand the way to move HYC in Wallet. How should it be done?

**Comment by arigatodl** [comment]
Hello @TetsuyaSuzuki, 

It seems that you are trying to run a full node. And that is not necessary to make transactions (such as receive hycon in your wallet). 
So now you can download the wallet app from https://github.com/Team-Hycon/hycon-gui/releases and you can choose the one that is suitable for your operating system. 
- macOS: hycon-wallet-desktop-1.0.0-mac.dmg
- windows: hycon-wallet-desktop-1.0.0-win.exe
- Linux 32 bit: hycon-wallet-desktop-1.0.0-linux-i386.AppImage
- Linux 64 bit: hycon-wallet-desktop-1.0.0-linux-x86_64.AppImage

Let me know how it goes. If you don't reply in 7 days, I will close this issue as resolved.

Regards,
Dulguun

**Comment by TetsuyaSuzuki** [comment]
* windows: hycon-wallet-desktop-1.0.0-win.exe
My PC was Windows, so (windows: hycon-wallet-desktop-1.0.0-win.exe) this was chosen and downloaded.

----- Original Message -----

**Comment by TetsuyaSuzuki** [comment]
Please teach me

**Comment by TetsuyaSuzuki** [comment]
My HYCON isn't reflected by wallet.
When wallet of a main page is clicked.
wallet.hycon.io is no longer supported.
For your safety and security, please visit our Medium article for instructions to claim your wallet for coin distribution. Indication goes out.

When a navigation bar is clicked, a screen of Lite Wallet goes out, but (pending: 0 HYCON) is indicated this in wallet. It was operated as a procedure many times, but it's a condition of pending. How should it be done to put hycon in Wallet?


----- Original Message -----

**Comment by TetsuyaSuzuki** [comment]
My HYCON isn't reflected by wallet.
When wallet of a main page is clicked.
wallet.hycon.io is no longer supported.
For your safety and security, please visit our Medium article for instructions to claim your wallet for coin distribution. Indication goes out.

When a navigation bar is clicked, a screen of Lite Wallet goes out, but (pending: 0 HYCON) is indicated this in wallet. It was operated as a procedure many times, but it's a condition of pending. How should it be done to put hycon in Wallet?

**Comment by TetsuyaSuzuki** [comment]
My HYCON isn't reflected by wallet.
When wallet of a main page is clicked.
wallet.hycon.io is no longer supported.
For your safety and security, please visit our Medium article for instructions to claim your wallet for coin distribution. Indication goes out.

When a navigation bar is clicked, a screen of Lite Wallet goes out, but (pending: 0 HYCON) is indicated this in wallet. It was operated as a procedure many times, but it's a condition of pending. How should it be done to put hycon in Wallet?
When (https://medium.com/@teamhycon/hycon-coin-distribution-b8e84f02e079) was clicked and it was made a procedure street, but that tries to input passward to the back command screen which clicked lunch for step 5, a command screen goes off, and I can't process it until the end.
How should it be done to pay HYC in HYCON wallet? I'm very worried.

**Comment by arigatodl** [comment]
@TetsuyaSuzuki 

After you open the application, you have 2 options.
1. Recover your wallet using mnemonic phrase.
![Recover wallet](https://user-images.githubusercontent.com/5443021/44644023-97084b00-aa0d-11e8-8514-b99054c21960.gif)
2. Create a new wallet.
![Add wallet](https://user-images.githubusercontent.com/5443021/44644087-d2a31500-aa0d-11e8-84bb-b433885f6fdf.gif)

And regarding KYC. It is better to ask it on our telegram channel (https://t.me/teamhycon) since it is not related to our desktop app.
